  name: failing workflow
  on: push
  jobs:
    failing_job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Failing job!"
        - run: exit 1
    wont_run:
      runs-on: ubuntu-latest
      steps:
        - run: echo "I should not run!"
      needs: [failing_job]