  name: Release workflow
  on:
    push:
      branches:
        - main
  jobs:
    Release:
      runs-on: ubuntu-latest
      steps:
        - name: Install git
          run: |
            apt update -y
            apt install git -y
        - name: Checkout
          uses: actions/checkout@v4
          with:
            persist-credentials: false
            fetch-depth: 0
        - name: Increment version
          run: ./increment_version.sh --major
        - name: Commit
          run: |
            git config --local user.email "be-meet-bot@example.com"
            git config --local user.name "be-meet-bot"
            git add version.txt
            git commit -m "Incremented version"
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}